name: Terraform-Plan-Incline-Infra-Plan

on:
  push:

jobs:
  validate:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}} ## Terraform expects this variable to be set
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_KEY}} ## Terraform expects this variable to be set
      AWS_REGION: 'us-east-1'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentinals_token: $ {{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init -no-color

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'push'
        run: terraform plan -no-color
